project:
  type: website
  output-dir: docs
  resources:
    - robots.txt
    - CNAME

website:
  title: "Van Galen Lab"
  description: "The Van Galen Lab at Brigham and Women's Hospital, Harvard Medical School, and the Broad Institute studies blood stem cells, aging, and leukemia."
  site-url: https://vangalenlab.org
  favicon: "images/favicon.svg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: papers.qmd
        text: Papers
      - href: resources.qmd
        text: Resources
      - href: people.qmd
        text: People
      - href: forest.qmd
        text: Forest
      - href: support.qmd
        text: Support
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "© 2025 Van Galen Lab • All Rights Reserved — [Privacy Policy](https://www.massgeneralbrigham.org/en/notices/web-privacy-policy) • Built with [Quarto](https://quarto.org/) • Shared on [GitHub](https://github.com/petervangalen/vangalenlab)"
    right:
      - icon: github
        href: https://github.com/petervangalen/vangalenlab
        target: _blank
      - text: "<img src='/images/bluesky.png' style='width:14px; height:14px; filter: brightness(0) invert(1); vertical-align: middle; margin-top: -3px'>"
        href: https://bsky.app/profile/vangalenlab.bsky.social
        target: _blank
      - icon: envelope
        href: mailto:pvangalen@bwh.harvard.edu

format:
  html:
    css: styles.css
    theme: flatly
    link-external-newwindow: true
    canonical-url: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

sitemap: true